name: amiidex
version: 1.0.0+10
description: An app to manage a Nintendo Amiibo collection.
author: Christophe Bonello
homepage: https://github.com/cbonello/
repository: https://github.com/cbonello/amiidex
issue_tracker: https://github.com/cbonello/amiidex/issues

environment:
  sdk: ">=2.4.0 <3.0.0"
  flutter: ^1.7.0

dependencies:
  flutter:
    sdk: flutter
  barcode_scan: ^1.0.0
  cupertino_icons: ^0.1.2
  dynamic_theme: ^1.0.1
  fl_chart: ^0.2.2
  floating_search_bar: ^0.2.0
  flutter_i18n: ^0.6.4
  flutter_markdown: ^0.2.0
  get_it: ^3.0.0+1
  intl: ^0.15.8
  introduction_screen: ^1.0.6
  launch_review: ^2.0.0
  package_info: ^0.4.0+6
  provider: ^3.1.0
  shared_preferences: ^0.5.3+4
  sprintf: ^4.0.2
  url_launcher: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1
  http: ^0.12.0+2
  mockito: ^4.1.0
  pedantic: ^1.8.0+1

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/images/logo_app.png

flutter:
  uses-material-design: true

  fonts:
    # https://www.wfonts.com/font/bauhaus#files
    - family: bauhaus
      fonts:
        - asset: fonts/bauhhl.ttf
          weight: 700

  assets:
    - assets/json/config.json
    - assets/text/privacy.md
    - assets/images/logo_app.png
    - assets/images/logo_drawer.png
    - assets/images/splash/controller_dark.png
    - assets/images/splash/controller_light.png
    - assets/images/splash/mario.png
    - assets/images/onboarding/series_filter.png
    - assets/images/onboarding/lock.png
    - assets/images/onboarding/long_press.png
    - assets/images/onboarding/double_tap.png
    - assets/images/onboarding/barcode_scan.png
    - assets/images/onboarding/swipe.png
    - assets/images/regions/ar.png
    - assets/images/regions/at.png
    - assets/images/regions/au.png
    - assets/images/regions/be.png
    - assets/images/regions/br.png
    - assets/images/regions/ca.png
    - assets/images/regions/ch.png
    - assets/images/regions/cl.png
    - assets/images/regions/co.png
    - assets/images/regions/cz.png
    - assets/images/regions/de.png
    - assets/images/regions/dk.png
    - assets/images/regions/es.png
    - assets/images/regions/eu.png
    - assets/images/regions/fi.png
    - assets/images/regions/fr.png
    - assets/images/regions/gb.png
    - assets/images/regions/gr.png
    - assets/images/regions/hk.png
    - assets/images/regions/hu.png
    - assets/images/regions/ie.png
    - assets/images/regions/il.png
    - assets/images/regions/it.png
    - assets/images/regions/jp.png
    - assets/images/regions/kr.png
    - assets/images/regions/mx.png
    - assets/images/regions/nl.png
    - assets/images/regions/no.png
    - assets/images/regions/nz.png
    - assets/images/regions/cn.png
    - assets/images/regions/sg.png
    - assets/images/regions/pe.png
    - assets/images/regions/pl.png
    - assets/images/regions/pt.png
    - assets/images/regions/ru.png
    - assets/images/regions/se.png
    - assets/images/regions/tw.png
    - assets/images/regions/us.png
    - assets/images/regions/za.png
    - assets/images/ac/header.jpg
    - assets/images/ac/logo.png
    - assets/images/ac/box_blathers.png
    - assets/images/ac/box_celeste.png
    - assets/images/ac/box_cyrus.png
    - assets/images/ac/box_digby.png
    - assets/images/ac/box_isabelle_summer_outfit.png
    - assets/images/ac/box_isabelle_winter_outfit.png
    - assets/images/ac/box_kapp_n.png
    - assets/images/ac/box_kicks.png
    - assets/images/ac/box_kk.png
    - assets/images/ac/box_lottie.png
    - assets/images/ac/box_mabel.png
    - assets/images/ac/box_reese.png
    - assets/images/ac/box_resetti.png
    - assets/images/ac/box_rover.png
    - assets/images/ac/box_timmy_tommy.png
    - assets/images/ac/box_tom_nook.png
    - assets/images/ac/blathers.png
    - assets/images/ac/box_bdl_cyrus_kk_reese.png
    - assets/images/ac/box_bdl_digby_isabelle_winter_outfit.png
    - assets/images/ac/celeste.png
    - assets/images/ac/cyrus.png
    - assets/images/ac/digby.png
    - assets/images/ac/isabelle_summer_outfit.png
    - assets/images/ac/isabelle_winter_outfit.png
    - assets/images/ac/kapp_n.png
    - assets/images/ac/kicks.png
    - assets/images/ac/kk.png
    - assets/images/ac/lottie.png
    - assets/images/ac/mabel.png
    - assets/images/ac/reese.png
    - assets/images/ac/resetti.png
    - assets/images/ac/rover.png
    - assets/images/ac/timmy_tommy.png
    - assets/images/ac/tom_nook.png
    - assets/images/dbl/header.jpg
    - assets/images/dbl/logo.png
    - assets/images/dbl/box_loot_goblin.png
    - assets/images/dbl/loot_goblin.png
    - assets/images/bb/header.jpg
    - assets/images/bb/logo.png
    - assets/images/bb/box_qbby.png
    - assets/images/bb/qbby.png
    - assets/images/cmh/header.jpg
    - assets/images/cmh/logo.png
    - assets/images/cmh/box_berioros_and_ayuria.png
    - assets/images/cmh/box_lioleia_and_cheval.png
    - assets/images/cmh/box_navirou.png
    - assets/images/cmh/box_one_eyed_liolaeus_and_rider_boy.png
    - assets/images/cmh/box_one_eyed_liolaeus_and_rider_girl.png
    - assets/images/cmh/box_qurupeco_and_dan.png
    - assets/images/cmh/berioros_and_ayuria.png
    - assets/images/cmh/lioleia_and_cheval.png
    - assets/images/cmh/navirou.png
    - assets/images/cmh/one_eyed_liolaeus_and_rider_boy.png
    - assets/images/cmh/one_eyed_liolaeus_and_rider_girl.png
    - assets/images/cmh/qurupeco_and_dan.png
    - assets/images/cr/header.jpg
    - assets/images/cr/logo.png
    - assets/images/cr/box_chibi_robo.png
    - assets/images/cr/chibi_robo.png
    - assets/images/dks/header.jpg
    - assets/images/dks/logo.png
    - assets/images/dks/box_solaire_of_astora.png
    - assets/images/dks/solaire_of_astora.png
    - assets/images/dpk/header.jpg
    - assets/images/dpk/logo.png
    - assets/images/dpk/box_detective_pikachu.png
    - assets/images/dpk/detective_pikachu.png
    - assets/images/fe/header.jpg
    - assets/images/fe/logo.png
    - assets/images/fe//box_alm.png
    - assets/images/fe//box_celica.png
    - assets/images/fe//box_chrom.png
    - assets/images/fe//box_tiki.png
    - assets/images/fe/alm.png
    - assets/images/fe/celica.png
    - assets/images/fe/chrom.png
    - assets/images/fe/tiki.png
    - assets/images/krb/header.jpg
    - assets/images/krb/logo.png
    - assets/images/krb/box_kirby.png
    - assets/images/krb/box_king_dedede.png
    - assets/images/krb/box_meta_knight.png
    - assets/images/krb/box_waddle_dee.png
    - assets/images/krb/kirby.png
    - assets/images/krb/king_dedede.png
    - assets/images/krb/meta_knight.png
    - assets/images/krb/waddle_dee.png
    - assets/images/mgmce/header.jpg
    - assets/images/mgmce/logo.png
    - assets/images/mgmce/box_mega_man_gold.png
    - assets/images/mgmce/mega_man_gold.png
    - assets/images/mtr/header.jpg
    - assets/images/mtr/logo.png
    - assets/images/mtr/box_metroid.png
    - assets/images/mtr/box_samus_aran.png
    - assets/images/mtr/metroid.png
    - assets/images/mtr/samus_aran.png
    - assets/images/pkm/header.jpg
    - assets/images/pkm/logo.png
    - assets/images/pkm/box_pikmin.png
    - assets/images/pkm/pikmin.png
    - assets/images/sk/header.jpg
    - assets/images/sk/logo.png
    - assets/images/sk/box_shovel_knight.png
    - assets/images/sk/shovel_knight.png
    - assets/images/skl/header.jpg
    - assets/images/skl/logo.png
    - assets/images/skl/box_hammer_slam_bowser.png
    - assets/images/skl/box_turbo_charge_donkey_kong.png
    - assets/images/skl/hammer_slam_bowser.png
    - assets/images/skl/turbo_charge_donkey_kong.png
    - assets/images/sm/header.jpg
    - assets/images/sm/logo.png
    - assets/images/sm/box_boo.png
    - assets/images/sm/box_bowser.png
    - assets/images/sm/box_daisy.png
    - assets/images/sm/box_diddy_kong.png
    - assets/images/sm/box_donkey_kong.png
    - assets/images/sm/box_goomba.png
    - assets/images/sm/box_koopa_troopa.png
    - assets/images/sm/box_luigi.png
    - assets/images/sm/box_mario_gold_edition.png
    - assets/images/sm/box_mario_silver_edition.png
    - assets/images/sm/box_mario.png
    - assets/images/sm/box_peach.png
    - assets/images/sm/box_rosalina.png
    - assets/images/sm/box_toad.png
    - assets/images/sm/box_waluigi.png
    - assets/images/sm/box_wario.png
    - assets/images/sm/box_yoshi.png
    - assets/images/sm/boo.png
    - assets/images/sm/bowser.png
    - assets/images/sm/daisy.png
    - assets/images/sm/diddy_kong.png
    - assets/images/sm/donkey_kong.png
    - assets/images/sm/goomba.png
    - assets/images/sm/koopa_troopa.png
    - assets/images/sm/luigi.png
    - assets/images/sm/mario_gold_edition.png
    - assets/images/sm/mario_silver_edition.png
    - assets/images/sm/mario.png
    - assets/images/sm/peach.png
    - assets/images/sm/rosalina.png
    - assets/images/sm/toad.png
    - assets/images/sm/waluigi.png
    - assets/images/sm/wario.png
    - assets/images/sm/yoshi.png
    - assets/images/smb30/header.jpg
    - assets/images/smb30/logo.png
    - assets/images/smb30/box_mario_classic_color.png
    - assets/images/smb30/box_mario_modern_color.png
    - assets/images/smb30/mario_classic_color.png
    - assets/images/smb30/mario_modern_color.png
    - assets/images/smo/header.jpg
    - assets/images/smo/logo.png
    - assets/images/smo/box_bowser_wedding_outfit.png
    - assets/images/smo/box_mario_cereal.png
    - assets/images/smo/box_mario_wedding_outfit.png
    - assets/images/smo/box_peach_wedding_outfit.png
    - assets/images/smo/bowser_wedding_outfit.png
    - assets/images/smo/mario_cereal.png
    - assets/images/smo/mario_wedding_outfit.png
    - assets/images/smo/peach_wedding_outfit.png
    - assets/images/spl/header.jpg
    - assets/images/spl/logo.png
    - assets/images/spl/box_callie.png
    - assets/images/spl/box_inkling_boy_1.png
    - assets/images/spl/box_inkling_boy_2.png
    - assets/images/spl/box_inkling_boy_3.png
    - assets/images/spl/box_inkling_girl_1.png
    - assets/images/spl/box_inkling_girl_2.png
    - assets/images/spl/box_inkling_girl_3.png
    - assets/images/spl/box_inkling_squid_1.png
    - assets/images/spl/box_inkling_squid_2.png
    - assets/images/spl/box_inkling_squid_3.png
    - assets/images/spl/box_marie.png
    - assets/images/spl/box_marina.png
    - assets/images/spl/box_octoling_boy.png
    - assets/images/spl/box_octoling_girl.png
    - assets/images/spl/box_octoling_octopus.png
    - assets/images/spl/box_pearl.png
    - assets/images/spl/box_bdl_inkling_boy_girl_squid.png
    - assets/images/spl/box_bdl_octoling_boy_girl_octopus.png
    - assets/images/spl/box_bdl_pearl_marina.png
    - assets/images/spl/callie.png
    - assets/images/spl/inkling_boy_1.png
    - assets/images/spl/inkling_boy_2.png
    - assets/images/spl/inkling_boy_3.png
    - assets/images/spl/inkling_girl_1.png
    - assets/images/spl/inkling_girl_2.png
    - assets/images/spl/inkling_girl_3.png
    - assets/images/spl/inkling_squid_1.png
    - assets/images/spl/inkling_squid_2.png
    - assets/images/spl/inkling_squid_3.png
    - assets/images/spl/marie.png
    - assets/images/spl/marina.png
    - assets/images/spl/octoling_boy.png
    - assets/images/spl/octoling_girl.png
    - assets/images/spl/octoling_octopus.png
    - assets/images/spl/pearl.png
    - assets/images/ssb/header.png
    - assets/images/ssb/logo.png
    - assets/images/ssb/box_bayonetta.png
    - assets/images/ssb/box_bayonetta_player_2.png
    - assets/images/ssb/box_bowser.png
    - assets/images/ssb/box_bowser_jr.png
    - assets/images/ssb/box_captain_falcon.png
    - assets/images/ssb/box_chrom.png
    - assets/images/ssb/box_cloud_player_2.png
    - assets/images/ssb/box_cloud.png
    - assets/images/ssb/box_corrin_player_2.png
    - assets/images/ssb/box_corrin.png
    - assets/images/ssb/box_daisy.png
    - assets/images/ssb/box_charizard.png
    - assets/images/ssb/box_dark_pit.png
    - assets/images/ssb/box_diddy_kong.png
    - assets/images/ssb/box_donkey_kong.png
    - assets/images/ssb/box_dr_mario.png
    - assets/images/ssb/box_duck_hunt.png
    - assets/images/ssb/box_falco.png
    - assets/images/ssb/box_fox.png
    - assets/images/ssb/box_ganondorf.png
    - assets/images/ssb/box_greninja.png
    - assets/images/ssb/box_ice_climbers.png
    - assets/images/ssb/box_ike.png
    - assets/images/ssb/box_incineroar.png
    - assets/images/ssb/box_inkling.png
    - assets/images/ssb/box_isabelle.png
    - assets/images/ssb/box_ivysaur.png
    - assets/images/ssb/box_jigglypuff.png
    - assets/images/ssb/box_ken.png
    - assets/images/ssb/box_king_dedede.png
    - assets/images/ssb/box_king_k_rool.png
    - assets/images/ssb/box_kirby.png
    - assets/images/ssb/box_link.png
    - assets/images/ssb/box_little_mac.png
    - assets/images/ssb/box_lucario.png
    - assets/images/ssb/box_lucas.png
    - assets/images/ssb/box_lucina.png
    - assets/images/ssb/box_luigi.png
    - assets/images/ssb/box_mario.png
    - assets/images/ssb/box_marth.png
    - assets/images/ssb/box_mega_man.png
    - assets/images/ssb/box_meta_knight.png
    - assets/images/ssb/box_mewtwo.png
    - assets/images/ssb/box_mii_brawler.png
    - assets/images/ssb/box_mii_gunner.png
    - assets/images/ssb/box_mii_swordfighter.png
    - assets/images/ssb/box_mr_game_watch.png
    - assets/images/ssb/box_ness.png
    - assets/images/ssb/box_pac_man.png
    - assets/images/ssb/box_palutena.png
    - assets/images/ssb/box_peach.png
    - assets/images/ssb/box_pichu.png
    - assets/images/ssb/box_pikachu.png
    - assets/images/ssb/box_olimar.png
    - assets/images/ssb/box_piranha_plant.png
    - assets/images/ssb/box_pit.png
    - assets/images/ssb/box_pokémon_trainer.png
    - assets/images/ssb/box_ridley.png
    - assets/images/ssb/box_robin.png
    - assets/images/ssb/box_rob_famicom.png
    - assets/images/ssb/box_rob_nes.png
    - assets/images/ssb/box_rosalina_luma.png
    - assets/images/ssb/box_roy.png
    - assets/images/ssb/box_ryu.png
    - assets/images/ssb/box_samus.png
    - assets/images/ssb/box_sheik.png
    - assets/images/ssb/box_shulk.png
    - assets/images/ssb/box_simon.png
    - assets/images/ssb/box_snake.png
    - assets/images/ssb/box_sonic.png
    - assets/images/ssb/box_squirtle.png
    - assets/images/ssb/box_toon_link.png
    - assets/images/ssb/box_villager.png
    - assets/images/ssb/box_wario.png
    - assets/images/ssb/box_wii_fit_trainer.png
    - assets/images/ssb/box_wolf.png
    - assets/images/ssb/box_yoshi.png
    - assets/images/ssb/box_young_link.png
    - assets/images/ssb/box_zelda.png
    - assets/images/ssb/box_zero_suit_samus.png
    - assets/images/ssb/bayonetta.png
    - assets/images/ssb/bayonetta_player_2.png
    - assets/images/ssb/bowser.png
    - assets/images/ssb/bowser_jr.png
    - assets/images/ssb/captain_falcon.png
    - assets/images/ssb/chrom.png
    - assets/images/ssb/cloud_player_2.png
    - assets/images/ssb/cloud.png
    - assets/images/ssb/corrin_player_2.png
    - assets/images/ssb/corrin.png
    - assets/images/ssb/daisy.png
    - assets/images/ssb/charizard.png
    - assets/images/ssb/dark_pit.png
    - assets/images/ssb/diddy_kong.png
    - assets/images/ssb/donkey_kong.png
    - assets/images/ssb/dr_mario.png
    - assets/images/ssb/duck_hunt.png
    - assets/images/ssb/falco.png
    - assets/images/ssb/fox.png
    - assets/images/ssb/ganondorf.png
    - assets/images/ssb/greninja.png
    - assets/images/ssb/ice_climbers.png
    - assets/images/ssb/ike.png
    - assets/images/ssb/incineroar.png
    - assets/images/ssb/inkling.png 
    - assets/images/ssb/isabelle.png
    - assets/images/ssb/ivysaur.png
    - assets/images/ssb/jigglypuff.png
    - assets/images/ssb/ken.png
    - assets/images/ssb/king_dedede.png
    - assets/images/ssb/king_k_rool.png
    - assets/images/ssb/kirby.png
    - assets/images/ssb/link.png
    - assets/images/ssb/little_mac.png
    - assets/images/ssb/lucario.png
    - assets/images/ssb/lucas.png
    - assets/images/ssb/lucina.png
    - assets/images/ssb/luigi.png
    - assets/images/ssb/mario.png
    - assets/images/ssb/marth.png
    - assets/images/ssb/mega_man.png
    - assets/images/ssb/meta_knight.png
    - assets/images/ssb/mewtwo.png
    - assets/images/ssb/mii_brawler.png
    - assets/images/ssb/mii_gunner.png
    - assets/images/ssb/mii_swordfighter.png
    - assets/images/ssb/mr_game_watch.png
    - assets/images/ssb/ness.png
    - assets/images/ssb/pac_man.png
    - assets/images/ssb/palutena.png
    - assets/images/ssb/peach.png
    - assets/images/ssb/pichu.png
    - assets/images/ssb/pikachu.png
    - assets/images/ssb/olimar.png
    - assets/images/ssb/piranha_plant.png
    - assets/images/ssb/pit.png
    - assets/images/ssb/pokémon_trainer.png
    - assets/images/ssb/ridley.png
    - assets/images/ssb/robin.png
    - assets/images/ssb/rob_famicom.png
    - assets/images/ssb/rob_nes.png
    - assets/images/ssb/rosalina_luma.png
    - assets/images/ssb/roy.png
    - assets/images/ssb/ryu.png
    - assets/images/ssb/samus.png
    - assets/images/ssb/sheik.png
    - assets/images/ssb/shulk.png
    - assets/images/ssb/simon.png
    - assets/images/ssb/snake.png
    - assets/images/ssb/sonic.png
    - assets/images/ssb/squirtle.png
    - assets/images/ssb/toon_link.png
    - assets/images/ssb/villager.png
    - assets/images/ssb/wario.png
    - assets/images/ssb/wii_fit_trainer.png
    - assets/images/ssb/wolf.png
    - assets/images/ssb/yoshi.png
    - assets/images/ssb/young_link.png
    - assets/images/ssb/zelda.png
    - assets/images/ssb/zero_suit_samus.png
    - assets/images/zld/header.jpg
    - assets/images/zld/logo.png
    - assets/images/zld/box_bokoblin.png
    - assets/images/zld/box_daruk.png
    - assets/images/zld/box_guardian.png
    - assets/images/zld/box_link_archer.png
    - assets/images/zld/box_link_rider.png
    - assets/images/zld/box_mipha.png
    - assets/images/zld/box_revali.png
    - assets/images/zld/box_urbosa.png
    - assets/images/zld/box_wolf_link.png
    - assets/images/zld/box_zelda.png
    - assets/images/zld/box_link_awakening.png
    - assets/images/zld/box_link_majora_s_mask.png
    - assets/images/zld/box_link_ocarina_of_time.png
    - assets/images/zld/box_link_skyward_sword.png
    - assets/images/zld/box_link_the_legend_of_zelda.png
    - assets/images/zld/box_link_twilight_princess.png
    - assets/images/zld/box_toon_link_the_wind_waker.png
    - assets/images/zld/box_zelda_the_wind_waker.png
    - assets/images/zld/bokoblin.png
    - assets/images/zld/daruk.png
    - assets/images/zld/guardian.png
    - assets/images/zld/link_archer.png
    - assets/images/zld/link_rider.png
    - assets/images/zld/mipha.png
    - assets/images/zld/revali.png
    - assets/images/zld/urbosa.png
    - assets/images/zld/wolf_link.png
    - assets/images/zld/zelda.png
    - assets/images/zld/link_awakening.png
    - assets/images/zld/link_majora_s_mask.png
    - assets/images/zld/link_ocarina_of_time.png
    - assets/images/zld/link_skyward_sword.png
    - assets/images/zld/link_the_legend_of_zelda.png
    - assets/images/zld/link_twilight_princess.png
    - assets/images/zld/toon_link_the_wind_waker.png
    - assets/images/zld/zelda_the_wind_waker.png
    - assets/images/yww/header.jpg
    - assets/images/yww/logo.png
    - assets/images/yww/box_green_yarn_yoshi.png
    - assets/images/yww/box_light_blue_yarn_yoshi.png
    - assets/images/yww/box_mega_yarn_yoshi.png
    - assets/images/yww/box_pink_yarn_yoshi.png
    - assets/images/yww/box_poochy.png
    - assets/images/yww/green_yarn_yoshi.png
    - assets/images/yww/light_blue_yarn_yoshi.png
    - assets/images/yww/mega_yarn_yoshi.png
    - assets/images/yww/pink_yarn_yoshi.png
    - assets/images/yww/poochy.png
